-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RIFA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `RIFA` ;

-- -----------------------------------------------------
-- Schema RIFA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RIFA` DEFAULT CHARACTER SET utf8 ;
USE `RIFA` ;

-- -----------------------------------------------------
-- Table `RIFA`.`PREMIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`PREMIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(255) NOT NULL,
  `VALOR` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`PROMOCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`PROMOCAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `DATA_INICIO` DATE NOT NULL,
  `DATA_FIM` DATE NOT NULL,
  `DATA_SORTEIO` DATE NOT NULL,
  `ARRECADACAO` DOUBLE NOT NULL,
  `VALOR_RIFA` DOUBLE NOT NULL,
  `PREMIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PROMOCAO_PREMIO1_idx` (`PREMIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROMOCAO_PREMIO1`
    FOREIGN KEY (`PREMIO_ID`)
    REFERENCES `RIFA`.`PREMIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`TIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`TIPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`VENDEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`VENDEDOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `CELULAR` INT NOT NULL,
  `LOGIN` VARCHAR(16) NOT NULL,
  `SENHA` VARCHAR(255) NOT NULL,
  `TIPO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_VENDEDOR_TIPO1_idx` (`TIPO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_VENDEDOR_TIPO1`
    FOREIGN KEY (`TIPO_ID`)
    REFERENCES `RIFA`.`TIPO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`COMPRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`COMPRADOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `CELULAR` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`NUMEROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`NUMEROS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NUMERO` INT NOT NULL,
  `PROMOCAO_ID` INT NOT NULL,
  `VENDEDOR_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_NUMEROS_PROMOCAO1_idx` (`PROMOCAO_ID` ASC) VISIBLE,
  INDEX `fk_NUMEROS_VENDEDOR1_idx` (`VENDEDOR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_NUMEROS_PROMOCAO1`
    FOREIGN KEY (`PROMOCAO_ID`)
    REFERENCES `RIFA`.`PROMOCAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NUMEROS_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_ID`)
    REFERENCES `RIFA`.`VENDEDOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`VENDA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA_VENDA` DATE NOT NULL,
  `VALOR` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`NUMEROS_COMPRADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`NUMEROS_COMPRADOS` (
  `COMPRADOR_ID` INT NOT NULL,
  `NUMEROS_ID` BIGINT NOT NULL,
  `VENDA_ID` INT NOT NULL,
  PRIMARY KEY (`COMPRADOR_ID`, `NUMEROS_ID`),
  INDEX `fk_COMPRADOR_has_NUMEROS_NUMEROS1_idx` (`NUMEROS_ID` ASC) VISIBLE,
  INDEX `fk_COMPRADOR_has_NUMEROS_COMPRADOR1_idx` (`COMPRADOR_ID` ASC) VISIBLE,
  INDEX `fk_NUMEROS_COMPRADOS_VENDA1_idx` (`VENDA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRADOR_has_NUMEROS_COMPRADOR1`
    FOREIGN KEY (`COMPRADOR_ID`)
    REFERENCES `RIFA`.`COMPRADOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRADOR_has_NUMEROS_NUMEROS1`
    FOREIGN KEY (`NUMEROS_ID`)
    REFERENCES `RIFA`.`NUMEROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NUMEROS_COMPRADOS_VENDA1`
    FOREIGN KEY (`VENDA_ID`)
    REFERENCES `RIFA`.`VENDA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RIFA`.`RESULTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RIFA`.`RESULTADO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `PROMOCAO_ID` INT NOT NULL,
  `NUMEROS_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RESULTADO_PROMOCAO1_idx` (`PROMOCAO_ID` ASC) VISIBLE,
  INDEX `fk_RESULTADO_NUMEROS1_idx` (`NUMEROS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RESULTADO_PROMOCAO1`
    FOREIGN KEY (`PROMOCAO_ID`)
    REFERENCES `RIFA`.`PROMOCAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESULTADO_NUMEROS1`
    FOREIGN KEY (`NUMEROS_ID`)
    REFERENCES `RIFA`.`NUMEROS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
